### PR TITLE
Register

### PR DESCRIPTION
**Pull request by ivanko22**

### CODE REVIEW

**Comment by MorganLee909** [comment]
I'm not even going to look at this until you remove all changes from "api". You do not edit a single line in the backend.

**Comment by ivanko22** [comment]
It was console.log on user.js and port on app.js which we changed together. Now it was back to the previous state.

**Comment by MorganLee909** [comment]
You have added packages. Both the package.json and package-lock.json in api/ have changes. Undo all of it. Go to "Files Changed" tab at the top of this page to see the diff.

**Comment by ivanko22** [comment]
Done

**Comment by MorganLee909** [comment]
app.js and user.js still have changes. You added/removed lines. So you basically editted my formating. I am not going to accept this at all. I want absolutely 0 changes to the backend. I am not going to go through and clean up my backend after you edit it every time.

**Comment by ivanko22** [comment]
I fixed it.

**Comment by MorganLee909** [comment]
Looks good. I have two things I just want to mention to you. 

1. The route in the address bar is a bit funky, with addresses such as "http://localhost:8000/#/sign-up" and "http://localhost:8000/#/sign-in".  Look into "vue-router" to solve this problem. I have already done it, so I can help if you need it.

2. It is unclear what is required for the password. It just says bad password.

If you are fine with this and want to fix those things in the future, that is fine. Let me know and I will merge it when you are ready.

**Comment by MorganLee909** [comment]
Also, responsiveness. The register form looks good. The landing page needs some tweeks. Up to you to fix it now or later though.

**Comment by ivanko22** [comment]
To me it looks okay for now. Will make this fixes in the next merge request with log in / log out. 
Thanks

**Pull request merged**
