### PR TITLE
Login

### PR DESCRIPTION
**Pull request by ivanko22**

### CODE REVIEW

**Comment by ivanko22** [comment]
@MorganLee909 Please merge

**Comment by MorganLee909** [comment]
1. Remove all `console.log()` statements. You have 4 of them in there.
2. Logout doesn't work. You are pointing to `/logout`, you need `/api/logout`.
3. You are displaying the "logged in page" even when login fails.

Also, when you create a pull request, please briefly describe the changes, not just "please merge". If I don't know what you have changed then I can't check it.

**Comment by ivanko22** [comment]
Fixed according to comments

**Comment by ivanko22** [comment]
@MorganLee909 Please review. Everything is fixed according to your comments.

**Comment by MorganLee909** [comment]
I still can't logout.

**Comment by ivanko22** [comment]
@MorganLee909 fixed logout

**Pull request merged**
